### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by Maath** [infocentric/restApiNodeDemo#1]
I am trying to run the demo api but I got the following javascript error,
(index):61 TypeError: Cannot read property 'map' of null
    at (index):45
    at async Promise.all (:8080/index 1)
Could you please help me to fix this ?
Thank you.

**Comment by Sakai-san** [comment]
Hello Maath. The rest endpoint `/posts` replies with a `null` instead of sending an array of posts. Probably `Sequelize` cannot do request to your database or you do not have any data in your database.

**Comment by Sakai-san** [comment]
@Maath Sequelize deprecated findById. You have to use findByPk instead in the models.

**Comment by Maath** [comment]
Thank you @Sakai-san .
